import { streamChat } from '../llm/index.js';

const REPORT_SYSTEM = `You are a senior penetration tester writing the EXECUTIVE SUMMARY of a
pentest report for a client. Be concise and professional (180-260 words). Summarize the
overall risk posture, the most important findings by severity, and high-level recommended
actions. Plain prose, no markdown headings, no code blocks.`;

function esc(s) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

const SEV_ORDER = ['critical', 'high', 'medium', 'low', 'info'];

async function aiExecSummary(session, findings, stats) {
  const top = findings
    .slice(0, 25)
    .map((f) => `- [${f.severity}] ${f.title}${f.cve ? ' (' + f.cve + ')' : ''}`)
    .join('\n');
  const prompt = `Target/scope: ${session.target || session.title || 'engagement'}.
Findings counts: ${JSON.stringify(stats)}.
Findings:\n${top || '(none)'}\n\nWrite the executive summary.`;
  try {
    const text = await streamChat({ history: [{ role: 'user', content: prompt }], system: REPORT_SYSTEM, onDelta: () => {} });
    if (text && text.trim().length > 40) return text.trim();
  } catch {
    /* fall through to template */
  }
  // Templated fallback.
  const risk = stats.critical ? 'critical' : stats.high ? 'high' : stats.medium ? 'moderate' : 'low';
  return `This assessment of ${session.title || 'the target'} identified ${stats.total} finding(s): ` +
    `${stats.critical} critical, ${stats.high} high, ${stats.medium} medium, ${stats.low} low, ${stats.info} informational. ` +
    `The overall risk is assessed as ${risk}. Prioritise remediation of the critical and high severity issues, ` +
    `then address medium/low items as part of routine hardening.`;
}

function findingsMarkdown(findings) {
  if (!findings.length) return '_No findings recorded._';
  const lines = ['| Severity | CVSS | Title | Host | Service | CVE | Status |', '|---|---|---|---|---|---|---|'];
  for (const f of findings) {
    lines.push(
      `| ${f.severity} | ${f.cvss_score ?? ''} | ${(f.title || '').replace(/\|/g, '\\|')} | ${f.host || ''} | ${f.service || ''} | ${f.cve || ''} | ${f.status || 'open'} |`
    );
  }
  return lines.join('\n');
}

function detailsMarkdown(findings) {
  return findings
    .filter((f) => f.severity !== 'info')
    .map((f, i) => {
      const parts = [`### ${i + 1}. ${f.title}`, `- **Severity:** ${f.severity}${f.cvss_score ? ` (CVSS ${f.cvss_score})` : ''}`];
      if (f.host) parts.push(`- **Affected:** ${f.host}${f.port ? ':' + f.port : ''} ${f.service || ''}`);
      if (f.cve) parts.push(`- **CVE:** ${f.cve}`);
      if (f.evidence) parts.push(`- **Evidence:**\n\n\`\`\`\n${f.evidence.slice(0, 800)}\n\`\`\``);
      if (f.remediation) parts.push(`- **Remediation:** ${f.remediation}`);
      return parts.join('\n');
    })
    .join('\n\n');
}

export async function generateReport(session, findings, stats) {
  const summary = await aiExecSummary(session, findings, stats);
  const date = new Date().toISOString().slice(0, 10);
  const sorted = [...findings].sort(
    (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity)
  );

  const markdown = `# Penetration Test Report — ${session.title || 'Engagement'}

**Date:** ${date}
**Session:** ${session.id}

## Executive Summary

${summary}

## Findings Summary

- Critical: ${stats.critical}
- High: ${stats.high}
- Medium: ${stats.medium}
- Low: ${stats.low}
- Informational: ${stats.info}
- **Total: ${stats.total}**

## Findings Overview

${findingsMarkdown(sorted)}

## Detailed Findings

${detailsMarkdown(sorted) || '_No non-informational findings._'}

## Methodology

Reconnaissance → enumeration → vulnerability identification → analysis. Findings were
collected by CypherMind AI tooling during the session and validated where possible.

---
*Generated by CypherMind AI on ${date}. For authorized security testing only.*
`;

  const html = toHtml(session, summary, sorted, stats, date);
  return { markdown, html, title: `Pentest Report — ${session.title || 'Engagement'}` };
}

const SEV_COLOR = { critical: '#ef4444', high: '#f59e0b', medium: '#eab308', low: '#3b82f6', info: '#9ca3af' };

function toHtml(session, summary, findings, stats, date) {
  const rows = findings
    .map(
      (f) => `<tr>
      <td><span class="sev" style="background:${SEV_COLOR[f.severity] || '#9ca3af'}">${esc(f.severity)}</span></td>
      <td>${f.cvss_score ?? ''}</td>
      <td>${esc(f.title)}</td>
      <td>${esc(f.host || '')}${f.port ? ':' + f.port : ''}</td>
      <td>${esc(f.service || '')}</td>
      <td>${f.cve ? esc(f.cve) : ''}</td>
      <td>${esc(f.status || 'open')}</td>
    </tr>`
    )
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8"><title>Pentest Report — ${esc(session.title || 'Engagement')}</title>
<style>
  body{font-family:Inter,Segoe UI,Arial,sans-serif;max-width:900px;margin:2rem auto;padding:0 1.5rem;color:#111827;line-height:1.55}
  h1{border-bottom:3px solid #06b6d4;padding-bottom:.4rem}
  h2{margin-top:2rem;color:#0e7490}
  .meta{color:#6b7280;font-size:.9rem}
  .cards{display:flex;gap:.5rem;flex-wrap:wrap;margin:1rem 0}
  .card{flex:1;min-width:90px;border:1px solid #e5e7eb;border-radius:10px;padding:.6rem;text-align:center}
  .card b{display:block;font-size:1.6rem}
  table{border-collapse:collapse;width:100%;font-size:.9rem;margin-top:.5rem}
  th,td{border:1px solid #e5e7eb;padding:.45rem .6rem;text-align:left;vertical-align:top}
  th{background:#f9fafb}
  .sev{color:#fff;border-radius:6px;padding:.1rem .45rem;font-size:.75rem;text-transform:uppercase}
  pre{background:#0d1117;color:#e6edf3;padding:.8rem;border-radius:8px;overflow:auto;font-size:.8rem}
  @media print{body{margin:0}}
</style></head><body>
<h1>Penetration Test Report</h1>
<div class="meta">${esc(session.title || 'Engagement')} &middot; ${date} &middot; session ${esc(session.id)}</div>
<h2>Executive Summary</h2><p>${esc(summary).replace(/\n/g, '<br>')}</p>
<h2>Findings Summary</h2>
<div class="cards">
  <div class="card" style="border-color:${SEV_COLOR.critical}"><b>${stats.critical}</b>Critical</div>
  <div class="card" style="border-color:${SEV_COLOR.high}"><b>${stats.high}</b>High</div>
  <div class="card" style="border-color:${SEV_COLOR.medium}"><b>${stats.medium}</b>Medium</div>
  <div class="card" style="border-color:${SEV_COLOR.low}"><b>${stats.low}</b>Low</div>
  <div class="card"><b>${stats.info}</b>Info</div>
</div>
<h2>Findings</h2>
<table><thead><tr><th>Severity</th><th>CVSS</th><th>Title</th><th>Host</th><th>Service</th><th>CVE</th><th>Status</th></tr></thead>
<tbody>${rows || '<tr><td colspan="7">No findings.</td></tr>'}</tbody></table>
<h2>Detailed Findings</h2>
${findings.filter((f) => f.severity !== 'info').map((f, i) => `<h3>${i + 1}. ${esc(f.title)}</h3>
<p><b>Severity:</b> ${esc(f.severity)}${f.cvss_score ? ` (CVSS ${f.cvss_score})` : ''}${f.cve ? ` &middot; <b>CVE:</b> ${esc(f.cve)}` : ''}<br>
${f.host ? `<b>Affected:</b> ${esc(f.host)}${f.port ? ':' + f.port : ''} ${esc(f.service || '')}<br>` : ''}
${f.remediation ? `<b>Remediation:</b> ${esc(f.remediation)}` : ''}</p>
${f.evidence ? `<pre>${esc(f.evidence.slice(0, 800))}</pre>` : ''}`).join('') || '<p>No non-informational findings.</p>'}
<hr><p class="meta">Generated by CypherMind AI on ${date}. For authorized security testing only.</p>
</body></html>`;
}
